apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: sb-provider
spec:
  provider: azure
  secretObjects:
  - secretName: sbconn-secret
    type: Opaque
    data:
      - objectName: servicebusconn
        key: key
  - secretName: sbtopic-secret
    type: Opaque
    data:
      - objectName: servicebustopic
        key: key
  parameters:
    usePodIdentity: "true"
    keyvaultName: "{{ .Values.keyVaultName }}" # the name of the KeyVault
    tenantId: "{{ .Values.keyVaultTenantId }}"
    objects: |
      array:
        - |
          objectName: servicebusconn
          objectType: secret
        - |
          objectName: servicebustopic
          objectType: secret
