# Default values for helium.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
labels:
  replicaCount: 1
  
  image:
    repository: retaildevcrew
    name: helium-csharp
    tag: stable
    pullPolicy: IfNotPresent
  
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 4120
  
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:4120;
        proxy_hide_header l5d-remote-ip;
        proxy_hide_header l5d-server-id;
    hosts:
      - host: 52.230.216.170.nip.io
        paths: /
  
    tls: []
  
  resources: 
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  nodeSelector: {}
  
  tolerations: []
  
  affinity: {}
  
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    metricName: response_per_second
    metricTargetValue: 4
  